name: 'Update Base Images'
description: 'Updates versions of the base images in all buildah.sh files in the repository. Afterwards it makes commit and push in specified branch.'

inputs:
  branch:
    description: 'The branch of the repository to checkout.'
    required: true
  to-version:
    description: 'Version of the new base images as short sha.'
    required: true
  image-repo:
    description: 'Type of the base image: base/base-config/jdk/jemalloc'
    required: true
  filename:
    description: 'The name of buildah file to look for.'
    required: false
    default: "buildah.sh"

outputs:
  old-version:
    description: 'The old base image version.'
    value: ${{ steps.current-version.outputs.version }}

runs:
  using: "composite"
  steps:
  - name: Checkout temporary branch
    uses: actions/checkout@v3
    with:
      ref: ${{ inputs.branch }}

  - name: Get current version
    shell: bash
    id: current-version
    run: |
      # Find a current version hash in any buildah.sh file 
      BUILDAH_FILE=$(find . -name ${{ inputs.filename }})
      for file in "${BUILDAH_FILE[@]}"
      do
        VERSION=$(cat $file | grep -Po '(?<=from_image="docker\.io\/portworx\/${{ inputs.image-repo }}:).*[0-9a-f]{7}' | grep -Po "[0-9a-f]{7}")
        if [ -n VERSION ]
        then
            echo "::set-output name=version::${VERSION}"
            break
        fi
      done

  - name: Find and Replace
    id: replace
    uses: jacobtomlinson/gha-find-replace@v2
    with:
      find: ${{ steps.current-version.outputs.version }}
      replace: ${{ inputs.to-version }}
      include: "**${{ inputs.filename }}"

  - name: Commit and Push
    if: ${{ steps.replace.outputs.modifiedFiles > 0 }}
    uses: EndBug/add-and-commit@v7
    with:
      message: |
        Update base images from `${{ steps.current-version.outputs.version }}` to `${{ inputs.to-version }}`
      branch: ${{ inputs.branch }}
      default_author: github_actions